;; extends

; SEE: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/README.md#adding-queries
; SEE: https://github.com/nvim-treesitter/nvim-treesitter#highlight

; Good references:
; https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/python
; https://github.com/tree-sitter/tree-sitter-python/tree/master/queries/

; How this works:
; SEE: https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax
; also check out :InspectTree

(ellipsis) @ellipsis
(none) @none

(class_definition
  name: (identifier) @type.definition)

(class_definition
  superclasses: (argument_list
    (identifier) @type.inherited))

; Raw strings are almost always used in context of regula expressions
; Here it's better to add the highlighting than not
(string
  (string_start) @_raw_string_start
  (string_content) @string.regexp
  (#lua-match? @_raw_string_start "r"))

; TODO: builtin version of @variable.member
; @constant.builtin
; ((identifier) @foo (#set! "type" "parameter"))
; ((identifier) @foo (#set! @foo "kind" "parameter"))
; ((node1) @left (node2) @right (#set! "type" "pair"))
; ((codeblock) @markup.raw.block (#set! "priority" 90))

; list generated by ./after/queries/python/generate_groups.py
((identifier) @dunder.builtin
  (#any-of? @dunder.builtin
"__future__" "__cached__" "__debug__" "__file__" "__import__" "__loader__" "__name__" "__package__" "__path__" "__spec__" "__subclasshook__" "__anext__" "__init__" "__cause__" "__context__" "__notes__" "__suppress_context__" "__traceback__" "__bases__" "__instancecheck__" "__mro__" "__subclasscheck__" "__subclasses__" "__missing__" "__iter__" "__enter__" "__exit__" "__next__" "__version__" "__post_init__" "__format__" "__str__" "__qualname__" "__type_params__" "__eq__" "__ne__" "__call__" "__getitem__" "__bytes__" "__contains__" "__delitem__" "__len__" "__setitem__" "__dir__" "__init_subclass__" "__new__" "__repr__" "__members__" "__reversed__" "__and__" "__or__" "__xor__" "__ceil__" "__floor__" "__round__" "__annotations__" "__closure__" "__code__" "__defaults__" "__dict__" "__doc__" "__globals__" "__kwdefaults__" "__module__" "__args__" "__origin__" "__parameters__" "__unpacked__" "__truediv__" "__class__" "__del__" "__func__" "__self__" "__abs__" "__add__" "__aenter__" "__aexit__" "__aiter__" "__await__" "__bool__" "__buffer__" "__class_getitem__" "__complex__" "__delattr__" "__delete__" "__divmod__" "__float__" "__floordiv__" "__ge__" "__get__" "__getattr__" "__getattribute__" "__getnewargs__" "__getnewargs_ex__" "__getstate__" "__gt__" "__hash__" "__iadd__" "__iand__" "__ifloordiv__" "__ilshift__" "__imatmul__" "__imod__" "__imul__" "__index__" "__int__" "__invert__" "__ior__" "__ipow__" "__irshift__" "__isub__" "__itruediv__" "__ixor__" "__le__" "__length_hint__" "__lshift__" "__lt__" "__match_args__" "__matmul__" "__mod__" "__mro_entries__" "__mul__" "__neg__" "__objclass__" "__pos__" "__pow__" "__radd__" "__rand__" "__rdivmod__" "__reduce__" "__reduce_ex__" "__release_buffer__" "__rfloordiv__" "__rlshift__" "__rmatmul__" "__rmod__" "__rmul__" "__ror__" "__rpow__" "__rrshift__" "__rshift__" "__rsub__" "__rtruediv__" "__rxor__" "__set__" "__set_name__" "__setattr__" "__setstate__" "__slots__" "__sub__" "__trunc__" "__fspath__" "__builtins__" "__sizeof__")
  (#set! "priority" 110)
)

